server:
  port: 7000
spring:
  application:
    name: pay-system-transaction-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  application:
    name: pay-system-transaction-service
  registry:
    address: nacos://127.0.0.1:8848
